### ISSUE TITLE
Реализовать экран обучения

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#10]
В данном окне должны быть сделаны
- [x] Окошко со словом
- [x] Кнопка "Посмотреть перевод"
- [x] Кнопка "Не помнил"
- [x] Кнопка "Помнил"

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23
