### ISSUE TITLE
Реализовать экран настроек

### ISSUE THREAD

**Issue by ildan95** [V3416TheRealRTZ/e-reader-dict#11]
- [ ] Реализовать кнопку добавления оффлайн словаря. 
- [ ] Реализовать checkbox для выбора словаря, из которого осуществляется поиск.
- [x] Реализовать кнопки на панели задач:
  - Обучение
  - Чтения
  - История переводов
  - Справка

**Comment by KraftJrIvo** [comment]
Используя бесплатный API переводчика, невозможно скачать весь словарь. И там нет никакой возможности выбирать словари. Поэтому пока что экран настроек вообще не нужен.

**Comment by ildan95** [comment]
В экране настроек можно выбирать между онлайн или каким-то конкретным оффлайн словарем. Выбор между онлайн словарями не предусмотрен. Т.е. в списке доступных словарей будет один единственный "онлайн словарь" и несколько оффлайн словарей.

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23
