### ISSUE TITLE
Реализована основная функциональность

### ISSUE THREAD

**Issue by KraftJrIvo** [V3416TheRealRTZ/e-reader-dict#14]
Кроме всего, что касается оффлайн словарей.

Продлеваем срок и допиливаем или оставляем так?

Ждем-с указаний.

**Comment by Lobachevskiy** [comment]
Версию на тестирование. Пока результатов ждем, оцените сколько времени уйдет на реализацию и обновите этот баг этой оценкой. Тогда и примем окончательное решение.

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23
