### ISSUE TITLE
Реализовать возможность перевода при помощи онлайн словаря

### ISSUE THREAD

**Issue by ildan95** [V3416TheRealRTZ/e-reader-dict#3]
- [x] Выбрать наиболее удобный (для реализации) сервис онлайн переводчика ( google, yandex и т.п.)
- [x] Реализовать функцию отправки слова для перевода по API
- [x] Реализовать обработку ответа на запрос по API

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23

**Comment by Lipetskikh** [comment]
Исправлено в версии 1.0.2.23.
