### ISSUE TITLE
Разрабатотать функциональность кнопок панели задач

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#4]
Список кнопок для реализации:
- [x] Обучение
- [x] Чтение
- [x] Настройки
- [x] Справка
- [x] Перейти на
- [x] История переводов

Подробное описание смотреть в спецификации

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Lobachevskiy** [comment]
При нажатии на кнопку "Перейти на страницу" приложение падает, если не введен номер страницы.

**Comment by KraftJrIvo** [comment]
Баг исправлен. Тестировать можно с версии 1.0.1.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23

**Comment by Lipetskikh** [comment]
Исправлено в версии 1.0.2.23.
