### ISSUE TITLE
Реализовать систему изучения слов

### ISSUE THREAD

**Issue by ildan95** [V3416TheRealRTZ/e-reader-dict#5]
- [x] Реализовать возможность добавление слова в "Обучение"
- [x] Реализовать возможность перехода слова на следующий этап 
- [x] Реализовать возможность перехода слова обратно на начальный этап
- [x] Реализовать фильтрацию списка слов для вывода на текущую дату

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23
