### ISSUE TITLE
Реализовать главный экран

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#6]
- [x] Реализовать кнопку "Добавить книгу"
- [x] Вывод списка добавленных книг

Описание содержимого находится в спецификации.

**Comment by ildan95** [comment]
Реализовать кнопку "Добавить книгу"

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Lobachevskiy** [comment]
Невозможно удалить книги из списка. Если файл добавлен по ошибке, то он там так и останется.

**Comment by Lipetskikh** [comment]
Насколько я понимаю, проблему решает кнопка "Сброс" в Настройках

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23

**Comment by Lipetskikh** [comment]
Исправлено в версии 1.0.2.23.
