### ISSUE TITLE
Реализовать экран чтения

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#7]
- [x] Экран с текстом книги. 
- [x] Возможность выделить слово и к выделенному слову должно прикрепляться всплывающее окошко с переводом. 
- [x] Во всплывающем окошке должна быть также кнопка "Учить"
- [x] Кнопки на панели задач:
  - Обучение
  - История переводов
  - Перейти на страницу
  - Настройки

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Lobachevskiy** [comment]
Проверено.
