### ISSUE TITLE
Реализовать экран истории переводов

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#8]
Реализовать:
- [x] Список с переводом слов и кнопкой "Учить"/"Добавлено"
- [x] Панель инструментов с кнопками:
  - Обучение
  - Чтение
  - Настройки
  - Справка

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Lobachevskiy** [comment]
При нажатии на кнопку "Учить" появляется строка "null null Уже в списке".

Кнопка "Учить" исчезает.

**Comment by Lipetskikh** [comment]
При открытии экрана истории переводов всегда есть "null null"

**Comment by KraftJrIvo** [comment]
Баг исправлен. Тестировать можно с версии 1.0.1.23

**Comment by Ionchenkova** [comment]
Тестировать можно с версии 1.0.2.23

**Comment by Lipetskikh** [comment]
Исправлено в версии 1.0.2.23.
