### ISSUE TITLE
Реализовать экран справки

### ISSUE THREAD

**Issue by elevir** [V3416TheRealRTZ/e-reader-dict#9]
На данном экране должна быть отображена информация о разработчиках и способах обратной связи с ними.

**Comment by KraftJrIvo** [comment]
Мне нужен конкретный текст справки.

**Comment by elevir** [comment]
Программисты: 
<Имя> <Фамилия> и/или <Псевдоним>
...
Дизайнеры:
<Имя> <Фамилия> и/или <Псевдоним>
...
E-mail для отзывов и предложений:
< e-mail >

<Ссылка> Оставить отзыв в Play market </Ссылка>

**Comment by ElenaKulikova** [comment]
Тестировать можно с версии 1.0.0.23

**Comment by Lobachevskiy** [comment]
Проверено.
